adds commit doc changes step

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -59,24 +59,17 @@ jobs:
         run: |
           sphinx-build -b singlehtml docs docs/_build
 
-      # - uses: actions/checkout@v1
-        # uses: ammaraskar/sphinx-action@master
-        # with:
-        #   build-command: "sphinx-build -b singlehtml . _build"
-        #   docs-folder: "docs/"
-      # -----------------------------------
-      # - name: Commit documentation changes
-      # -----------------------------------
-        # run: |
-        #   git clone https://github.com/robmacc/objectives.git --branch gh-pages --single-branch gh-pages
-        #   cp -r docs/_build/html/* gh-pages/
-        #   cd gh-pages
-        #   git config --local user.email "robmaccallum@gmail.com"
-        #   git config --local user.name "robmacc"
-        #   git add .
-        #   git commit -m "updates documentation" -a || true
-        #   # The above command will fail if no changes were present, so we ignore
-        #   # that.
+      - name: commit documentation changes
+        run: |
+          git clone https://github.com/robmacc/objectives.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          git config --local user.email "robmaccallum@gmail.com"
+          git config --local user.name "robmacc"
+          git add .
+          git commit -m "updates documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
       # -----------------------------------
       # - name: Push changes
       # -----------------------------------
